name: "ReDoT"
description: "Calls ChatGPT API to auto-generate docs and commits the response to the branch"
author: "Sefi Potashnik, Connor Rowland, Jason Warren"
inputs:
  owner:
    description: "Owner of the Repo"
    required: true
  repo:
    description: "Repo name"
    required: true
  pull:
    description: "Pull request number"
    required: true
  anthropic_api_key:
    description: "Anthropic API key"
    required: true
  github_token:
    description: "GitHub token to use if write permission is not set in workflow"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
